### ISSUE TITLE
Aston Martin MED17.7.x

### ISSUE THREAD

**Issue by brandonros** [jglim/UnlockECU#11]
It is very similar to Mercedes MED1775

Could you please e-mail me and we will exchange Discords to speak more quickly/freely? I have 85% of this done with your code (parameters) ready to go from a bench read/putting CBOOT for Aston Martin in GHidra but I am stuck on one part.

**Comment by jglim** [comment]
If possible, I would prefer communicating via issues here, as I only have a short/irregular window in my schedule to tend to my OSS projects. Unfortunately this also means that I do not have the ability to tend to near-realtime communications like Discord — sorry about that.

_If sensitive files are involved, you can check  [this thread for an email address](https://github.com/jglim/CaesarSuite/discussions/1#discussioncomment-316558). Please let me know if you send anything as that inbox is normally unmonitored._

**Comment by brandonros** [comment]
good luck 👍
