### ISSUE TITLE
Thinking out loud

### ISSUE THREAD

**Issue by Feezex** [jglim/UnlockECU#14]
There are a couple of areas - in which I have a personal interest.
The first concerns the seed. Please correct the statements to be false or true and add your statements.
</n>
1. The algorithm for calculating the seed is contained in the cbf or smr-d or dll extracted from them.
2. The key is checked by the target control unit with its firmware.
3. There is a hardware platform that can disassemble the control unit code in real time.
4. There is a software environment for virtual debugging and disassembly of the target control unit by loading real dumps into the virtual processor
4 .1. It is possible to use one of the working seed calculators in tandem with equipment working on this principle for decompilation

The second part relates to sonder hash (it may be another huge part of a project since it refers directly to ECU Unlocking) and all of the above statements are also applicable to it.
I'm tired of fighting with sonder hash, and I'm looking for more radical methods of its disclosure. Little is known to us today.
</n>

5. It is based on the RIPEMD N-101 (N-1).
6. It is cyclic.
7. Each subsequent hash is a new sonder.
8. The algorithm is the same for all FBS3 control units.
8.1. All FBS3 control units contain the same key verification algorithm and can be found in the ECU firmware.
9. The smaller the firmware, the easier it is to disassemble.
9.1. You need to sort the fbs3 firmware to find the smallest of them for subsequent work with them (debugging and disassembling)

**Comment by jglim** [comment]
- The algorithm for calculating the seed is contained in the cbf or smr-d or dll extracted from them.

As far as I understand, this is true for publicly-available algos. Traditionally, they are embedded as DLLs, sometimes they are proprietary scripts in CBFs, and in newer SMR-D containers, they are typically Java applications. Unfortunately the good stuff (such as high level unlocks) are seemingly never included in the diagnostic containers as the end-user should normally not require it.

- The key is checked by the target control unit with its firmware.

I'm not sure if I understand the question correctly, but usually it is the microcontroller that answers to the CAN request that handles the checking as well. For example, in the color IC204 devices, there are multiple processors: a NEC uC that handles the cluster-related tasks, and a more powerful uC (Toshiba Capricorn-*; the one that runs VxWorks) that handles the screen graphics. It is the NEC chip that handles the CAN communications, as well as the seed-key verification, and the Toshiba uC is completely uninvolved.

- There is a hardware platform that can disassemble the control unit code in real time.

Did you mean something like debugging over JTAG? In my limited experience (IC204), debugging and firmware readout is locked at the processor level, and the only way is to erase the chip. I am not aware of methods to work around this, so in that specific case, hardware approaches are not viable.
For other processor targets, there may be specialist tools for glitching the processor security bits to unlock debugging, but this is beyond my knowledge.

- There is a software environment for virtual debugging and disassembly of the target control unit by loading real dumps into the virtual processor

For the IC204, NEC (Renesas) actually has a disassembler/debugger/CPU emulator tool that is decent, however the relevant board definitions are deliberately removed, probably as part of a special agreement with the MB/VDO etc. At the end of the day, static analysis via Ghidra was the most effective approach for me.

- It is possible to use one of the working seed calculators in tandem with equipment working on this principle for decompilation

This was what I hoped to achieve with the NEC development tools, though it was still easier to just use Ghidra and stick to static analysis. Funnily, I did consider emulating the CPU, feeding it seed challenges, and reading the generated key from its memory.

---

Unfortunately I do not know enough of FBS/Sonder to add to it; I hope for you that someone might have more answers. Those are good questions that you raised, and it will be interesting to hear from more perspectives and experiences from others, especially for different architectures like Tricore.

**Comment by karakan08** [comment]
The algorithm for calculating the seed is contained in the cbf or smr-d or dll extracted from them. 
=> Correct, it can be found when using DTS monaco in a specific folder.

The key is checked by the target control unit with its firmware
=> don't think so as the firmware can change on an ECU for example but the seed key algorithm stays the same...

There are hardware platforms that can disassemble the control unit code in real time.
=> some tools do exsist that can read the eeprom directly without need of seedkey, if that's what you're asking.

**Comment by Feezex** [comment]
> The algorithm for calculating the seed is contained in the cbf or smr-d or dll extracted from them. => Correct, it can be found when using DTS monaco in a specific folder.
>**_Same with Vediamo, but not for all cbf/smr-d, huge part of them doesnt contain any security  dlls_**
> The key is checked by the target control unit with its firmware => don't think so as the firmware can change on an ECU for example but the seed key algorithm stays the same...
> **_I didnt say that something changes ecu. I say that seed key cheching procedure occurs in target ecu_**
> There are hardware platforms that can disassemble the control unit code in real time. => some tools do exsist that can read the eeprom directly without need of seedkey, if that's what you're asking.
No. Jglim got my idea. Reading with programmer is easy even for a scoolboy. Idea is using developer boards with special software to see all processes in CPU\memory in real time

**Comment by Feezex** [comment]
Dear @jglim i knew only you can make this done so i have a proposition. As i told before sonder is refers directly to ECU Unlocking so it must become another part of UnlockEcu standlone app. 
Thust must have short conversation with ecu\tcu\ism to make it virgin(clear personalisation\deactivate)
![prop](https://user-images.githubusercontent.com/75809563/147857094-051c3bad-af8c-4411-9533-d2abf03c2290.jpg)
This doesnt need to use alot cbf's, instead of that it will act like a script by sending previously configured sequence of can bus packets, Received data during script execution must fill data fields.
So only 2 buttons. First one script to read data. Another script to execute reset operation.
 Seems operation is the same for all engine ecu. For tcu \ ism we can work after getting working interface.
Key features:
- using j2534 instead of expensive tools for such operation
- user friendly standalone app
- **doesnt contain heavy process for hash calculation** ,  there is alot sonder calculation services that can calc password. Notlike seed - sonder doesnt have time limitations, so one day you can read sonder and after week you can input password and reset ecu to new state.

Have a traces of software to ecu dialog to implement that all. 
Appreciate your work and open source position. I whish we have small conversation by mail, anyway one day it'll become opensource. Knock on my mail please tdrivex@gmail.com

**Comment by mercikc55** [comment]
> * doesnt contain heavy process for hash calculation

Not sure, but without the base it is not possible to calculate the hash

**Comment by mercikc55** [comment]
> 5\. It is based on the RIPEMD N-101 (N-1)

Yes.

**Comment by ficho965** [comment]
@Feezex  & @jglim For educational purposes I can provide you sonder Hash for you ECU, so you can erase renew it etc, btw you will not be able to personalize it on bench and activate it afterwards since a specific procedure is needed, so the ecu accepts the FBS3 data you want to upload.
But if you place the ecu on car and with Xentry or also with some other tools you can start procedure for ecu personalization and activation so your car can start once again.
For Sonder Hash special  rainbow tables are used, no easy way to do Sonder Hash calculation.
regards Ficho

**Comment by Feezex** [comment]
Thanks, i do have access to make calc hashes.
But idea was about algo- the way FBS3 unit can check hashes in miliseconds

**Comment by ficho965** [comment]
Hi,
what do you mean by check ? find proper dealer hash for specific sonder hash ?
or to check if specific dealer hash fits some sonder hash.
since RIPEMD is used you know that this is a one way hash algo, no turning back, but if you might guess the initial value for specific sonder hash then this could be done in milliseconds since the max depth of sonder hash is 10000 hash turns...

**Comment by Feezex** [comment]
last hash will give result as starting hash .
>>>Thats what i called  'cyclic database', for now have 175 records(pairs).
and see what you will get as a result ( 0x65 times)
>>>Should it return again to string №1?

**Comment by jglim** [comment]
Hey @ficho965, thanks for your kind offer, though I don't have any fbs3 devices to take it up. That being said, I enjoy reading your in-depth discussion with Sergey. Cheers

**Comment by Feezex** [comment]
0102030405060708 - dont have password
0A52467AD2AF76AA -dont have password
D8FE9C9B76786563  -dont have password ,since each hash creates new one, i dont beleive its endless in cyclic code
8F7D2B42D9BFAC34 - no password
4A6CF856BF764C7B - no password
maybe you gived me EIS passwords?

**Comment by ficho965** [comment]
Hi, @Feezex to be clear, by password you mean erase password (RIPEMD -101)?

**Comment by ficho965** [comment]
RipeMD_101_(D759611A076BE6C1) -> 0A52467AD2AF76AA
RipeMD_101_(0A52467AD2AF76AA) -> D8FE9C9B76786563
RipeMD_101_(B4A2CCF439BC9DE1) -> 8F7D2B42D9BFAC34
Can not find for this one 4A6CF856BF764C7B it seems to be shallow not deep enough hash, and the other one 0102030405060708 I made it up as an initial value for creating a sonder hash.

**Comment by Feezex** [comment]
D759611A076BE6C1 > 0
B4A2CCF439BC9DE1 >0

**Comment by ficho965** [comment]
I use a tool that I have Extreme MB Tool, it is really good for Sonder Hash calculations.
VVDI, CGDI  sometime fail to find proper Sonder Hash, if you need some that you can not find I can check with my tool if it will find it.

**Comment by Feezex** [comment]
@ficho965  can you do me a favour.
Check this and calculate 5 next steps. 
05 56 D7 97 0A 6D 14 1D
F2 E2 EE D6 0B 97 AD 0A
DB 2D 17 90 F1 09 66 10

**Comment by ficho965** [comment]
Hi,
None of the above Hash's a real Sonder Hash to my opinion, because none of them was found when I did a search in DB.
Did you make up these hash's ? because I check 1 vs 2 vs 3 and they are 101 hash away.
What is your idea what do you want to try to achieve, quick Dealer Hash finder for some specific Sonder Hash ???
Have in mind that Sonder Hash has to fulfil some criteria to become a true Sonder Hash I would call it.
regards ficho

**Comment by Feezex** [comment]
do you need a proof?

**Comment by ficho965** [comment]
What kind of Proof?, if it is a real sonder Hash ? no need but none of them where found in Extreme MB Tool database.
you can send me a mail ficho965@gmail.com.
regards Ficho

**Comment by Feezex** [comment]
![image](https://user-images.githubusercontent.com/75809563/177325227-b3199af3-41a9-441a-8b45-f01722dd36fe.png)

**Comment by bergut** [comment]
So have real software for generating sonder hash? Because Autovei can't do all SID

**Comment by jakka351** [comment]
Bromigos! this is crazy!
