### ISSUE TITLE
CRD3 - level 01 - variant coding unlock

### ISSUE THREAD

**Issue by WSorban** [jglim/UnlockECU#15]
**ECU Name**
CRD3

**Source file**
https://dotnetfiddle.net/heBM7O

**Additional context**
This is actual CRD3 security level 01 algo, needed for changing variant coding parameters, such as remember start/stop.
Seed and key lengths: 4 bytes.
I do not take credit for reversing this. It was done by a guy named Aloulou, and shared on the forums, a long time ago.

Since level 01 is not part of the db, I'll add it here.

I tested and used it myself, on actual CRD3 ECU.

**Checklist**

I have checked that the requested definition does not exist in [db.json](https://github.com/jglim/UnlockECU/blob/main/UnlockECU/db.json) : Yes
_Some ECUs share a common definition, for example, the CRD3 family uses the CRD3NFZ definition, and are linked together with an [alias](https://github.com/jglim/UnlockECU/blob/bcb77faa30da1babce0aca79a2d63c99618226c2/UnlockECU/db.json#L2019). If an alias is missing, please use the "Bug Report" template instead._

**Comment by jglim** [comment]
Thank you for your contribution! The algo has been added and is now available [here](https://github.com/jglim/UnlockECU/blob/main/UnlockECU/UnlockECU/Security/PowertrainSecurityAlgo3.cs).
