### ISSUE TITLE
Incorrect seed length for ORC166

### ISSUE THREAD

**Issue by Flo354** [jglim/UnlockECU#32]
**Describe the bug**
Security Level 01 for ORC166 smr-d and UnlockECU defines that seed length is equal to 8.
![image](https://github.com/jglim/UnlockECU/assets/4249311/5e24f319-084a-45b5-9a9e-f42b48c4ad7a)

Actually, the seed length is 4 bytes

**To Reproduce**
With DTS Monaco, we get the following trace.
![image](https://github.com/jglim/UnlockECU/assets/4249311/e0d5b2f5-5b8c-41a7-bcf1-bf156c3dc25a)

As you can see, the seed length is 4 bytes.
If we look closely at the algorithm, we notice that only the first 4 bytes are used anyway.
![image](https://github.com/jglim/UnlockECU/assets/4249311/8fbcc253-737a-43b1-ae9f-217da39edc78)

**Additional context**
I used my own implementation to validate the seed/key.
I would advise to consider valid 4 bytes and 8 bytes in case another ECU variant gives an 8 bytes seed.

**Comment by jglim** [comment]
Thanks for digging into this. I've followed your suggestion to allow for both 4 and 8-byte seeds for the ORC166.
