### ISSUE TITLE
fscm gen5 missing 11 (0b)/17(11) levels

### ISSUE THREAD

**Issue by Feezex** [jglim/UnlockECU#49]
FSCM_GEN5

[FSCM_GEN5_0.zip](https://github.com/user-attachments/files/18118171/FSCM_GEN5_0.zip)
![image](https://github.com/user-attachments/assets/8300dd53-866f-4805-a56d-c4a360177bd5)
![image](https://github.com/user-attachments/assets/79ec0dfd-d0cb-4ef6-bc95-9949b2aefe49)
everything is correct

**Comment by jglim** [comment]
Added, thanks again Sergey
