### ISSUE TITLE
Updated the DB.json

### ISSUE THREAD

**Issue by ecumasterac** [jglim/UnlockECU#5]
There was a duplicate for a CPC_NG Entry. I fixed that.
[db.zip](https://github.com/jglim/UnlockECU/files/6005156/db.zip)

**Comment by jglim** [comment]
Looks good to me; added in https://github.com/jglim/UnlockECU/commit/67ea57be10a81665c4f5ad0dc4a1aff58793c0d1 . Thank you for your contribution, ecumasterac!
